<%@page isELIgnored="false" pageEncoding="UTF-8" contentType="text/html; UTF-8" %>
<div class="col-md-12 column">
    <table class="table">
        <thead>
        <tr>
            <th>
                交易总金额
            </th>
            <th>
                订单数量
            </th>
            <th>
                交易成功
            </th>
            <th>
                交易失败
            </th>
            <th>
                退款金额
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                1123
            </td>
            <td>
                232
            </td>
            <td>
                43344
            </td>
            <td>
                0
            </td>
            <td>
                0
            </td>
        </tr>
        </tbody>
    </table>
</div>