spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tfbook?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    #url: jdbc:mysql://localhost:3306/tfbook?useSSL=false

#设置单个或多个文件上传最大值
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB

#开发环境
  profiles:
    active: prod
#集成redis
  application:
    name: spring-boot-redis
  redis:
    database: 0 #Redis数据库索引 默认为0
    host: 192.168.74.138 #Redis服务器地址
    port: 7000
    timeout: 20000 #连接超时时间 毫秒
    pool:
      max-active: 1000 #连接池最大连接数
      min-idle: 1 #连接池最小空闲连接
      max-idle: 100
      max-wait: -1 # 连接池的最小空闲连接


#配置端口和应用名
server:
  jsp-servlet:
    init-parameters:
      development: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jz1501.chenhc.diploma.tfbook.entity

