spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tfbook
  http:
    encoding:
      charset: utf-8
      force: true
#开发环境
  profiles:
    active: prod
#配置端口和应用名
server:
  jsp-servlet:
    init-parameters:
      development: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jz1501.chenhc.diploma.tfbook.entity


